### ISSUE TITLE
app crashed to create new user

### ISSUE THREAD

**Issue by frbayart** [finoanamendrika/o3-article-app-backend#3]
```
query: SELECT `User`.`user_id` AS `User_user_id`, `User`.`username` AS `User_username` FROM `user` `User` WHERE (`User`.`username` = ?) LIMIT 1 -- PARAMETERS: ["priscilla"]
query: START TRANSACTION
query: INSERT INTO `user`(`user_id`, `username`) VALUES (DEFAULT, DEFAULT)
query failed: INSERT INTO `user`(`user_id`, `username`) VALUES (DEFAULT, DEFAULT)
error: Error: ER_NO_DEFAULT_FOR_FIELD: Field 'username' doesn't have a default value
    at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/app/node_modules/mysql/lib/Connection.js:198:25)
    at /app/node_modules/typeorm/src/driver/mysql/MysqlQueryRunner.ts:194:36
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlMessage: "Field 'username' doesn't have a default value",
  sqlState: 'HY000',
  index: 0,
  sql: 'INSERT INTO `user`(`user_id`, `username`) VALUES (DEFAULT, DEFAULT)'
}
query: ROLLBACK
/app/node_modules/typeorm/src/driver/mysql/MysqlQueryRunner.ts:222
                                new QueryFailedError(query, parameters, err),
                                ^
QueryFailedError: ER_NO_DEFAULT_FOR_FIELD: Field 'username' doesn't have a default value
    at Query.<anonymous> (/app/node_modules/typeorm/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/app/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:88:28) {
  query: 'INSERT INTO `user`(`user_id`, `username`) VALUES (DEFAULT, DEFAULT)',
  parameters: [],
  driverError: Error: ER_NO_DEFAULT_FOR_FIELD: Field 'username' doesn't have a default value
      at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
      at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
      at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
      at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
      at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
      at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
      at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:88:28)
      at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      --------------------
      at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
      at PoolConnection.query (/app/node_modules/mysql/lib/Connection.js:198:25)
      at /app/node_modules/typeorm/src/driver/mysql/MysqlQueryRunner.ts:194:36
      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'ER_NO_DEFAULT_FOR_FIELD',
    errno: 1364,
    sqlMessage: "Field 'username' doesn't have a default value",
    sqlState: 'HY000',
    index: 0,
    sql: 'INSERT INTO `user`(`user_id`, `username`) VALUES (DEFAULT, DEFAULT)'
  },
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlMessage: "Field 'username' doesn't have a default value",
  sqlState: 'HY000',
  index: 0,
  sql: 'INSERT INTO `user`(`user_id`, `username`) VALUES (DEFAULT, DEFAULT)'
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by finoanamendrika** [comment]
The issue is fixed. This is due to a problem of instantiation of the User class before calling the createUser function of the user.service, in the controller user.controller.
